---
- name: Create Baikal volumes
  community.docker.docker_volume:
    state: present
    name: "{{ item }}"
  loop: 
    - baikal_config
    - baikal_specific

- name: Run Baikal container
  community.docker.docker_container:
    name: baikal
    image: docker.io/ckulka/baikal:nginx
    state: started
    restart_policy: always
    network_mode: overlay_network
    volumes:
      - baikal_config:/var/www/baikal/config
      - baikal_specific:/var/www/baikal/Specific