---
- name: Create FreshRSS volumes
  community.docker.docker_volume:
    state: present
    name: "{{ item }}"
  loop: 
    - freshrss_extensions
    - freshrss_data

- name: Run FreshRSS container
  community.docker.docker_container:
    name: freshrss
    image: docker.io/freshrss/freshrss:alpine
    state: started
    restart_policy: always
    network_mode: overlay_network
    volumes:
      - freshrss_extensions:/var/www/FreshRSS/extensions
      - freshrss_data:/var/www/FreshRSS/data
    env:
      TZ: Europe/Paris
      CRON_MIN: "1,31"