---
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto
  tags: always

- name: Update & cleanup Debian based OS
  ansible.builtin.import_tasks: update_cleanup_debian.yml
  when: ansible_distribution in ["Ubuntu", "Debian"]
  tags: debian

- name: Update & cleanup Docker
  ansible.builtin.import_tasks: update_cleanup_docker.yml
  when: "'docker-ce' in ansible_facts.packages"
  tags: docker