---
- name: Update & cleanup Debian based OS
  ansible.builtin.import_tasks: update_cleanup_debian.yml
  when: ansible_distribution in ["Ubuntu", "Debian"]
  tags: debian

- name: Update & cleanup Docker
  ansible.builtin.import_tasks: update_cleanup_docker.yml
  when: inventory_hostname in groups['docker']
  tags: docker