---
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto
  tags: always

- ansible.builtin.import_tasks: debian.yml
  when: ansible_distribution in ["Ubuntu", "Debian"]
  tags: debian

- ansible.builtin.import_tasks: docker.yml
  when: "'docker-ce' in ansible_facts.packages"
  tags: docker