---
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Update apt packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: full
  when: ansible_distribution in ["Ubuntu", "Debian"]

- name: Remove dependencies
  ansible.builtin.apt:
    autoremove: yes
    purge: true
  when: ansible_distribution in ["Ubuntu", "Debian"]

- name: Prune Docker objects
  community.docker.docker_prune:
    containers: true
    images: true
    networks: true
    volumes: true
    builder_cache: true
  when: "'docker-ce' in ansible_facts.packages"