---
- name: Pull & recreate Docker containers
  ansible.builtin.include_role:
    name: docker_containers

- name: Prune Docker objects
  community.docker.docker_prune:
    containers: true
    images: true
    networks: true
    volumes: true
    builder_cache: true