---
- name: Install Crowdsec on Debian based OS
  ansible.builtin.import_tasks: install_debian.yml
  when: ansible_distribution in ["Ubuntu", "Debian"]
  tags: crowdsec,debian

- name: Template Crowdsec configuration
  ansible.builtin.template:
    src: "{{ item['src'] }}"
    dest: "{{ item['dest'] }}"
    mode: "{{ item['mode'] }}"
  loop:
    - { src: 'gotify.yaml.j2', dest: '/etc/crowdsec/notifications/gotify.yaml', mode: '0600' }
    - { src: 'profiles.yaml.j2', dest: '/etc/crowdsec/profiles.yaml', mode: '0644' }
  tags: crowdsec

- name: Reload Crowdsec service
  ansible.builtin.systemd_service:
    name: crowdsec.service
    state: reloaded
    scope: system
  tags: crowdsec

- name: Enroll Crowdsec Security Engine to the console
  ansible.builtin.command: "cscli console enroll -e context {{ crowdsec_enroll_token }}"
  when: crowdsec_enroll_token is defined
  tags: crowdsec,enroll