---
- name: Install Crowdsec dependencies
  ansible.builtin.package:
    name:
      - ca-certificates
      - curl
    state: present

- name: Add Crowdsec GPG key
  ansible.builtin.get_url:
    url: "https://packagecloud.io/crowdsec/crowdsec/gpgkey"
    dest: /etc/apt/keyrings/crowdsec_crowdsec-archive-keyring.gpg
    mode: '0644'

- name: Add Crowdsec repo
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
  loop:
    - "deb [signed-by=/etc/apt/keyrings/crowdsec_crowdsec-archive-keyring.gpg] https://packagecloud.io/crowdsec/crowdsec/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main"
    - "deb-src [signed-by=/etc/apt/keyrings/crowdsec_crowdsec-archive-keyring.gpg] https://packagecloud.io/crowdsec/crowdsec/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main"

- name: Install Crowdsec
  ansible.builtin.package:
    name:
      - crowdsec
      - crowdsec-firewall-bouncer-iptables
    state: present

- name: Enable Crowdsec service
  ansible.builtin.systemd:
    name: crowdsec.service
    state: started
    enabled: true
    scope: system