---
- name: Create FreshRSS volumes
  community.docker.docker_volume:
    state: present
    volume_name: "{{ item }}"
  loop:
    - freshrss_extensions
    - freshrss_data

- name: Run FreshRSS container
  community.docker.docker_container:
    name: freshrss
    image: docker.io/freshrss/freshrss:alpine
    state: started
    pull: always
    recreate: true
    restart_policy: unless-stopped
    networks:
      - name: traefik_network
    volumes:
      - freshrss_extensions:/var/www/FreshRSS/extensions
      - freshrss_data:/var/www/FreshRSS/data
    env:
      TZ: "{{ timezone }}"
      CRON_MIN: "1,31"
    labels:
      traefik.enable: "true"
      traefik.http.routers.freshrss.rule: Host(`rss.{{ traefik_domain }}`)
      traefik.http.routers.freshrss.entrypoints: "websecure"
      traefik.http.routers.freshrss.tls: "true"
      traefik.http.routers.freshrss.service: "freshrss"
      traefik.http.services.freshrss.loadbalancer.server.port: "80"