---
- name: Run Playit Agent
  community.docker.docker_container:
    name: playit-agent
    image: ghcr.io/playit-cloud/playit-agent:latest
    state: started
    pull: always
    recreate: true
    restart_policy: unless-stopped
    network_mode: host
    env:
        SECRET_KEY: "{{ playit_secret_key }}"