services:
  caddy: # Reverse Proxy
    image: caddy:alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data

  syncthing: # File server
    image: syncthing/syncthing
    restart: always
    volumes:
      - ./syncthing_data:/var/syncthing
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp

  wireguard: # VPN Server
    image: linuxserver/wireguard:latest
    restart: always
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - TZ=Europe/Paris
      - SERVERURL=wireguard.endlessazurite.fr
      - PEERS=red-taurus,cyan-fox
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - ./wireguard_config:/config
      - /lib/modules:/lib/modules
    ports:
      - "51820:51820/udp"

volumes:
  caddy_data: