services:
  caddy: # Reverse Proxy
    image: caddy:alpine
    hostname: caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile

  jellyfin: # Media Server
    image: jellyfin/jellyfin
    hostname: jellyfin
    restart: 'unless-stopped'
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache