services:
  caddy: # Reverse Proxy
    image: caddy:alpine
    hostname: caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile

  jellyfin: # Media Server
    image: jellyfin/jellyfin
    hostname: jellyfin
    restart: 'unless-stopped'
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache

  nextcloud: # Data Server
    image: linuxserver/nextcloud:latest
    hostname: nextcloud
    restart: unless-stopped
    environment:
      - TZ=Europe/Paris
    volumes:
      - ./nextcloud/config:/config
      - /nextcloud/data:/data