---
- name: Import swarm playbook
  ansible.builtin.import_playbook: playbooks/swarm.yml

- name: Import vpn playbook
  ansible.builtin.import_playbook: playbooks/vpn.yml

- name: Import production playbook
  ansible.builtin.import_playbook: playbooks/production.yml

- name: Import media playbook
  ansible.builtin.import_playbook: playbooks/media.yml

- name: Import games playbook
  ansible.builtin.import_playbook: playbooks/games.yml