---
- ansible.builtin.import_tasks: minecraft.yml
  tags: minecraft

- ansible.builtin.import_tasks: terraria.yml
  tags: terraria

- ansible.builtin.include_role:
    name: administration
    tasks_from: watchtower
    apply:
      tags:
        - watchtower
  tags: always