---
- ansible.builtin.import_tasks: minecraft.yml
  tags: minecraft,container

- ansible.builtin.import_tasks: terraria.yml
  tags: terraria,container

- ansible.builtin.import_tasks: dozzle-agent.yml
  tags: dozzle-agent,container

- ansible.builtin.include_role:
    name: applications
    tasks_from: watchtower
    apply:
      tags:
        - watchtower
        - container
  tags: always