---
- name: Create Minecraft directory
  ansible.builtin.file:
    path: "{{ docker.data }}/minecraft"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Run Minecraft server
  community.docker.docker_container:
    name: minecraft
    image: docker.io/itzg/minecraft-server:latest
    state: started
    restart_policy: always
    restart: true
    ports:
      - 25565:25565
    volumes:
      - "{{ docker.data }}/minecraft:/data"
    env:
      # General
      MEMORY: "3G"
      USE_AIKAR_FLAGS: "true"
      EULA: "true"
      ONLINE_MODE: "false"
      SNOOPER_ENABLED: "false"
      # Gameplay
      TYPE: "FABRIC"
      VERSION: "1.20.4"
      SERVER_NAME: "minecraft-survival"
      MOTD: "Serveur Poulet"
      DIFFICULTY: "normal"
      MODE: "survival"
      # World
      SPAWN_PROTECTION: "0"
      VIEW_DISTANCE: "8"
      SIMULATION_DISTANCE: "8"
      # Players
      MAX_PLAYERS: "8"
      FORCE_GAMEMODE: "true"
      ENABLE_WHITELIST: "true"
      # Mods
      MODRINTH_PROJECTS: "{{ minecraft_mods }}"