---
- name: Template Caddy configuration
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: "{{ volumes.caddy }}/Caddyfile"
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"
  tags: caddy

- name: Create Caddy volumes
  community.docker.docker_volume:
    state: present
    name: "{{ item }}"
  loop: 
    - caddy_data
    - caddy_config
  tags: caddy

- name: Run Caddy container
  community.docker.docker_container:
    name: caddy
    image: docker.io/library/caddy:alpine
    state: started
    restart_policy: always
    network_mode: overlay_network
    ports:
      - 80:80
      - 443:443
    volumes:
      - "{{ volumes.caddy }}/Caddyfile:/etc/caddy/Caddyfile"
      - caddy_data:/data
      - caddy_config:/config
  tags: caddy