---
- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg"
    state: present

- name: Add Docker repo
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"

- name: Install packages
  ansible.builtin.package:
    name: "{{ packages }}"
    state: present
  when: packages is defined

- name: Enable Systemd services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
    scope: system
  loop: "{{ services }}"
  when: services is defined

- name: Create volumes directories
  ansible.builtin.file:
    path: "{{ item.value }}"
    state: directory
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"
  loop: "{{ volumes|dict2items }}"
  when: volumes is defined