---
- name: Install packages
  ansible.builtin.package:
    name: "{{ packages }}"
    state: present
  when: packages is defined

- name: Enable Systemd services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
    scope: system
  loop: "{{ services }}"
  when: services is defined