---
- name: Update Debian-based OS
  ansible.builtin.apt:
    update_cache: true
    upgrade: full
  when: ansible_distribution in ["Ubuntu", "Debian"]

- name: Install packages
  ansible.builtin.package:
    name: "{{ packages }}"
    state: present
  when: packages is defined

- name: Enable Systemd services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
    scope: system
  loop: "{{ services }}"
  when: services is defined

- name: Create volumes directories
  ansible.builtin.file:
    path: "{{ item.value }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  loop: "{{ volumes|dict2items }}"
  when: volumes is defined