---
- name: Install packages
  ansible.builtin.package:
    name: "{{ packages }}"
    state: present
  when: packages is defined
  tags: common

- name: Enable Systemd services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
    scope: system
  loop: "{{ services }}"
  when: services is defined
  tags: common

- ansible.builtin.import_tasks: docker.yml
  tags: docker