---
- name: Add Firefly-iii cron job
  ansible.builtin.cron:
    name: Firefly-iii Cron Job
    job: "wget -qO- http://localhost:{{ ports.fireflyiii }}/api/v1/cron/{{ fireflyiii_token }}"
    minute: "0"
    hour: "3"
    user: "{{ remote_user }}"

- name: Create Firefly-iii volumes
  community.docker.docker_volume:
    state: present
    name: "{{ item }}"
  loop: 
    - fireflyiii_db
    - fireflyiii_upload

- name: Run Firefly-iii container
  community.docker.docker_container:
    name: firefly-iii
    image: docker.io/fireflyiii/core:latest
    state: started
    restart_policy: always
    ports:
      - "{{ ports.fireflyiii }}:8080/tcp"
    volumes:
      - fireflyiii_upload:/var/www/html/storage/upload
      - fireflyiii_db:/var/www/html/storage/database
    env:
      APP_ENV: local
      APP_KEY: "{{ fireflyiii_token }}"
      TZ: Europe/Paris
      DB_CONNECTION: sqlite
      STATIC_CRON_TOKEN: "{{ fireflyiii_token }}"
      TRUSTED_PROXIES: "**"