---
- name: Create Wireguard volume
  community.docker.docker_volume:
    state: present
    name: wireguard_data

- name: Run Wireguard container
  community.docker.docker_container:
    name: wireguard
    image: ghcr.io/wg-easy/wg-easy:latest
    state: started
    restart_policy: always
    capabilities:
      - NET_ADMIN
      - SYS_MODULE
      - NET_RAW
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
      net.ipv4.ip_forward: 1
    ports:
      - 51820:51820/udp
      - "{{ ports.wireguard }}:51821/tcp"
    volumes:
      - wireguard_data:/etc/wireguard:Z
    env:
      WG_HOST: home.dizzytopaz.fr
      PASSWORD: "{{ wg_password }}"