---
- ansible.builtin.import_tasks: wireguard.yml
  tags: wireguard

- ansible.builtin.import_tasks: portainer-agent.yml
  tags: portainer-agent,portainer

- ansible.builtin.import_tasks: watchtower.yml
  tags: watchtower