---
- name: Run Watchtower container
  community.docker.docker_container:
    name: watchtower
    image: docker.io/containrrr/watchtower:latest
    state: started
    restart_policy: always
    restart: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    env:
      WATCHTOWER_SCHEDULE: "0 0 3 * * FRI"
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_NOTIFICATIONS: "gotify"
      WATCHTOWER_NOTIFICATION_GOTIFY_URL: "https://gotify.{{ private_domain }}"
      WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN: "{{ watchtower_gotify_token }}"