---
- name: Create Gotify volume
  community.docker.docker_volume:
    state: present
    volume_name: gotify_data

- name: Run Gotify container
  community.docker.docker_container:
    name: gotify
    image: docker.io/gotify/server:latest
    state: started
    pull: always
    recreate: true
    restart_policy: unless-stopped
    networks:
      - name: traefik_network
    volumes:
      - gotify_data:/app/data
    env:
      GOTIFY_DEFAULTUSER_NAME: admin
      GOTIFY_DEFAULTUSER_PASS: "{{ gotify_password }}"
    labels:
      traefik.enable: "true"
      traefik.http.routers.gotify.rule: Host(`gotify.{{ traefik_domain }}`)
      traefik.http.routers.gotify.entrypoints: "websecure"
      traefik.http.routers.gotify.tls: "true"
      traefik.http.routers.gotify.service: "gotify"
      traefik.http.services.gotify.loadbalancer.server.port: "80"