---
- name: Create music directory
  ansible.builtin.file:
    path: "/srv/music"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0700'

- name: Create Jellyfin volumes
  community.docker.docker_volume:
    state: present
    volume_name: "{{ item }}"
  loop:
    - jellyfin_config
    - jellyfin_cache

- name: Run Jellyfin container
  community.docker.docker_container:
    name: jellyfin
    image: docker.io/jellyfin/jellyfin:latest
    state: started
    pull: always
    recreate: true
    restart_policy: always
    network_mode: traefik_network
    volumes:
      - jellyfin_config:/config
      - jellyfin_cache:/cache
      - /srv/music:/music
    labels:
      traefik.enable: "true"
      traefik.http.routers.jellyfin.rule: Host(`media.{{ traefik_domain }}`)
      traefik.http.routers.jellyfin.entrypoints: "https"
      traefik.http.routers.jellyfin.tls: "true"
      traefik.http.routers.jellyfin.service: "jellyfin"
      traefik.http.services.jellyfin.loadbalancer.server.port: "8096"