---
- name: Create Docker NFS volume for music files
  community.docker.docker_volume:
    state: present
    volume_name: music_nfs
    driver_options:
      type: "nfs"
      o: "addr={{ hostvars['vm-files-01']['ansible_host'] }},rw,nfsvers=4.2"
      device: ":/music"

- name: Create Jellyfin volumes
  community.docker.docker_volume:
    state: present
    volume_name: "{{ item }}"
  loop:
    - jellyfin_config
    - jellyfin_cache

- name: Run Jellyffin container
  community.docker.docker_container:
    name: jellyfin
    image: docker.io/jellyfin/jellyfin:latest
    state: started
    restart_policy: always
    recreate: true
    network_mode: traefik_network
    volumes:
      - jellyfin_config:/config
      - jellyfin_cache:/cache
      - music_nfs:/music
    labels:
      traefik.enable: "true"
      traefik.http.routers.jellyfin.rule: Host(`media.{{ traefik_domain }}`)
      traefik.http.routers.jellyfin.entrypoints: "https"
      traefik.http.routers.jellyfin.tls: "true"
      traefik.http.routers.jellyfin.service: "jellyfin"
      traefik.http.services.jellyfin.loadbalancer.server.port: "8096"