---
- name: Deploy Uptime-Kuma container
  ansible.builtin.import_tasks: uptime_kuma.yml
  when: inventory_hostname == "vm-docker-01"
  tags: uptime-kuma,uptime

- name: Deploy Gotify container
  ansible.builtin.import_tasks: gotify.yml
  when: inventory_hostname == "vm-docker-01"
  tags: gotify

- name: Deploy Baikal container
  ansible.builtin.import_tasks: baikal.yml
  when: inventory_hostname == "vm-docker-01"
  tags: baikal

- name: Deploy Actual Budget container
  ansible.builtin.import_tasks: actualbudget.yml
  when: inventory_hostname == "vm-docker-01"
  tags: actualbudget,actual

- name: Deploy FreshRSS container
  ansible.builtin.import_tasks: freshrss.yml
  when: inventory_hostname == "vm-docker-01"
  tags: freshrss

- name: Deploy Jellyfin container
  ansible.builtin.import_tasks: jellyfin.yml
  when: inventory_hostname == "vm-docker-01"
  tags: jellyfin

- name: Deploy Syncthing container
  ansible.builtin.import_tasks: syncthing.yml
  when: inventory_hostname == "vm-docker-01"
  tags: syncthing

- name: Deploy WG Easy container
  ansible.builtin.import_tasks: wireguard.yml
  when: inventory_hostname == "vm-docker-01"
  tags: wireguard

- name: Deploy Traefik container
  ansible.builtin.import_tasks: traefik.yml
  when: inventory_hostname == "vm-docker-01"
  tags: traefik

- name: Deploy Minecraft Server
  ansible.builtin.import_tasks: minecraft.yml
  when: inventory_hostname == "vm-games-01"
  tags: minecraft

- name: Deploy Playit Agent
  ansible.builtin.import_tasks: playit_agent.yml
  when: inventory_hostname == "vm-games-01"
  tags: playit,playit-agent