---
- name: Deploy Traefik container
  ansible.builtin.import_tasks: traefik.yml
  tags: docker,traefik

- name: Deploy Portainer container
  ansible.builtin.import_tasks: portainer.yml
  tags: docker,portainer

- name: Deploy Baikal container
  ansible.builtin.import_tasks: baikal.yml
  tags: docker,baikal

- name: Deploy Actual Budget container
  ansible.builtin.import_tasks: actualbudget.yml
  tags: docker,actual

- name: Deploy FreshRSS container
  ansible.builtin.import_tasks: freshrss.yml
  tags: docker,freshrss

- name: Deploy Jellyfin container
  ansible.builtin.import_tasks: jellyfin.yml
  tags: docker,jellyfin

- name: Deploy Syncthing container
  ansible.builtin.import_tasks: syncthing.yml
  tags: docker,syncthing

- name: Deploy WG Easy container
  ansible.builtin.import_tasks: wireguard.yml
  tags: docker,wireguard