---
- name: Create Wg-easy volume
  community.docker.docker_volume:
    state: present
    volume_name: wireguard_data

- name: Run Wg-easy container
  community.docker.docker_container:
    name: wireguard
    image: ghcr.io/wg-easy/wg-easy:15
    state: started
    pull: always
    recreate: true
    restart_policy: unless-stopped
    networks:
      - name: traefik_network
    ports:
      - 51820:51820/udp
    volumes:
      - wireguard_data:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    capabilities:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      net.ipv4.ip_forward: 1
      net.ipv4.conf.all.src_valid_mark: 1
      net.ipv6.conf.all.disable_ipv6: 0
      net.ipv6.conf.all.forwarding: 1
      net.ipv6.conf.default.forwarding: 1
    labels:
      traefik.enable: "true"
      traefik.http.routers.wireguard.rule: Host(`wg.{{ traefik_domain }}`)
      traefik.http.routers.wireguard.entrypoints: "websecure"
      traefik.http.routers.wireguard.service: "wireguard"
      traefik.http.services.wireguard.loadbalancer.server.port: "51821"