---
- name: Install Docker on Debian based OS
  ansible.builtin.import_tasks: install_docker_debian.yml
  when: ansible_distribution in ["Ubuntu", "Debian"]
  tags: docker,debian

- name: Create the reverse-proxy network
  community.docker.docker_network:
    name: traefik_network
  when: inventory_hostname == "vm-docker"
  tags: docker,network