---
- name: Create Syncthing directory
  ansible.builtin.file:
    path: "{{ directories.container }}/syncthing"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  register: syncthing

- name: Run Syncthing container
  community.docker.docker_container:
    name: syncthing
    image: docker.io/syncthing/syncthing:latest
    state: started
    restart_policy: always
    network_mode: overlay_network
    ports:
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    volumes:
      - "{{ syncthing.path }}:/var/syncthing"
    labels:
      traefik.enable: "true"
      traefik.http.routers.syncthing.rule: Host(`sync.{{ private_domain }}`)
      traefik.http.routers.syncthing.entrypoints: "https"
      traefik.http.routers.syncthing.tls: "true"
      traefik.http.routers.syncthing.service: "syncthing"
      traefik.http.services.syncthing.loadbalancer.server.port: "8384"