---
- name: Install backup packages
  ansible.builtin.package:
    name:
      - rclone
      - cron
    state: present

- name: Enable cron service
  ansible.builtin.systemd:
    name: cron.service
    state: started
    enabled: true
    scope: system

- name: Create daily backup with Rclone
  ansible.builtin.cron:
    name: "Send backup to remote storage"
    state: present
    minute: "0"
    hour: "2"
    user: "{{ ansible_user }}"
    job: "rclone sync --progress --stats-one-line --stats=2m {{ backup.source }} {{ backup.remote }}"