---
- name: Create Firefly-iii volumes
  community.docker.docker_volume:
    state: present
    name: "{{ item }}"
  loop: 
    - firefly_db
    - firefly_upload

- name: Run Cron container
  community.docker.docker_container:
    name: firefly_cron
    image: docker.io/library/alpine:latest
    state: started
    restart_policy: always
    network_mode: "{{ docker.network }}"
    command: sh -c "echo \"0 6 * * * wget -qO- http://firefly:8080/api/v1/cron/{{ fireflyiii_token }}\" | crontab - && crond -f -L /dev/stdout"

- name: Run Firefly-iii container
  community.docker.docker_container:
    name: firefly
    image: docker.io/fireflyiii/core:latest
    state: started
    restart_policy: always
    network_mode: "{{ docker.network }}"
    volumes:
      - firefly_upload:/var/www/html/storage/upload
      - firefly_db:/var/www/html/storage/database
    env:
      APP_ENV: production
      APP_KEY: "{{ fireflyiii_token }}"
      TZ: Europe/Paris
      DB_CONNECTION: sqlite
      MAIL_MAILER: log
      #APP_LOG_LEVEL: debug
      STATIC_CRON_TOKEN: "{{ fireflyiii_token }}"
      TRUSTED_PROXIES: "**"
    labels:
      traefik.enable: "true"
      traefik.http.routers.firefly.rule: Host(`firefly.{{ private_domain }}`)
      traefik.http.routers.firefly.entrypoints: "https"
      traefik.http.routers.firefly.tls: "true"
      traefik.http.routers.firefly.service: "firefly"
      traefik.http.services.firefly.loadbalancer.server.port: "8080"