---
- name: Create media directory
  ansible.builtin.file:
    path: "{{ docker.directory }}/media"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Create Jellyfin volumes
  community.docker.docker_volume:
    state: present
    name: "{{ item }}"
  loop:
    - jellyfin_config
    - jellyfin_cache

- name: Run Jellyfin container
  community.docker.docker_container:
    name: jellyfin
    image: docker.io/jellyfin/jellyfin:latest
    state: started
    restart_policy: always
    network_mode: "{{ docker.network }}"
    volumes:
      - "{{ docker.directory }}/media:/media"
      - jellyfin_config:/config
      - jellyfin_cache:/cache