---
- name: Create Syncthing directory
  ansible.builtin.file:
    path: "{{ docker.directory }}/syncthing"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Run Syncthing container
  community.docker.docker_container:
    name: syncthing
    image: docker.io/syncthing/syncthing:latest
    state: started
    restart_policy: always
    network_mode: "{{ docker.network }}"
    ports:
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    volumes:
      - "{{ docker.directory }}/syncthing:/var/syncthing"