---
- name: Install Samba & NFS packages
  ansible.builtin.apt:
    name:
      - samba
      - samba-vfs-modules
      - nfs-kernel-server
    state: present

- name: Enable Samba & NFS services
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: started
    enabled: true
    scope: system
  loop:
    - smbd.service
    - nmbd.service
    - nfs-server.service