---
- name: Install backup packages
  ansible.builtin.package:
    name:
      - rclone
      - cron
    state: present
  tags: backup

- name: Enable cron service
  ansible.builtin.systemd:
    name: cron.service
    state: started
    enabled: true
    scope: system
  tags: backup

- name: Template backup script
  ansible.builtin.template:
    src: offsite_backup.sh.j2
    dest: /usr/local/bin/offsite_backup.sh
    mode: '0700'
  tags: backup,script

- name: Create daily backup with Rclone
  ansible.builtin.cron:
    name: "Send backup to remote storage"
    state: present
    minute: "0"
    hour: "5"
    user: "{{ ansible_user }}"
    job: "/usr/local/bin/offsite_backup.sh"
  tags: backup,cron