---
- name: Create archive directory
  ansible.builtin.file:
    path: "{{ docker.directory }}/archive"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  tags: nfs

- name: Install NFS server
  ansible.builtin.package:
    name:
      - nfs-kernel-server
    state: present
  tags: nfs

- name: Enable NFS service
  ansible.builtin.systemd:
    name: nfs-server.service
    state: started
    enabled: true
    scope: system
  tags: nfs

- name: Template NFS configuration
  ansible.builtin.template:
    src: "exports.j2"
    dest: "/etc/exports"
  tags: nfs

- name: Restart NFS service
  ansible.builtin.systemd_service:
    state: restarted
    name: nfs-server.service
  tags: nfs