---
- name: Run Wireguard container
  containers.podman.podman_container:
    name: wireguard
    image: ghcr.io/wg-easy/wg-easy
    state: started
    restart_policy: always
    capabilities:
      - NET_ADMIN
      - SYS_MODULE
      - NET_RAW
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
      net.ipv4.ip_forward: 1
    ports:
      - 51820:51820/udp
      - 51821:51821/tcp
    volumes:
      - "{{ container_volumes.wireguard }}:/etc/wireguard:Z"
    env:
      WG_HOST: home.endlessazurite.fr
      PASSWORD: kPThOMOOZmSlvj6y1