---
- name: Init a new swarm
  community.docker.docker_swarm:
    state: present
  register: output_swarm
  when: inventory_hostname in groups['swarm'][0]
  tags: swarm

- name: Add manager nodes
  community.docker.docker_swarm:
    state: join
    join_token: "{{ hostvars[groups['swarm'][0]]['output_swarm']['swarm_facts']['JoinTokens']['Manager'] }}"
    remote_addrs: "{{ groups['swarm'][0] }}"
  when: inventory_hostname in groups['swarm'] and inventory_hostname not in groups['swarm'][0]
  tags: swarm

- name: Create overlay network
  community.docker.docker_network:
    name: overlay_network
    driver: overlay
    attachable: true
  when: inventory_hostname in groups['swarm'][0]
  tags: swarm