---
- name: Run Watchtower container
  community.docker.docker_container:
    name: watchtower
    image: docker.io/containrrr/watchtower:latest
    state: started
    restart_policy: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env:
      WATCHTOWER_SCHEDULE: "0 0 3 * * *"
      WATCHTOWER_CLEANUP: "true"