---
- ansible.builtin.import_tasks: wireguard.yml
  tags: wireguard,container

- ansible.builtin.import_tasks: portainer-agent.yml
  tags: portainer-agent,container

- ansible.builtin.include_role:
    name: applications
    tasks_from: watchtower
    apply:
      tags:
        - watchtower
        - container
  tags: always