---
- name: Create Wg-easy volume
  community.docker.docker_volume:
    state: present
    name: wireguard_data
  tags: wireguard,container

- name: Run Wg-easy container
  community.docker.docker_container:
    name: wireguard
    image: ghcr.io/wg-easy/wg-easy:latest
    state: started
    restart_policy: always
    restart: true
    ports:
      - 51820:51820/udp
      - 51821:51821/tcp
    volumes:
      - wireguard_data:/etc/wireguard
    capabilities:
      - NET_ADMIN
      - SYS_MODULE
      - NET_RAW
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
      net.ipv4.ip_forward: 1
    env:
      WG_HOST: "{{ public_domain }}"
      PASSWORD: "{{ wg_password }}"
      WG_ALLOWED_IPS: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['network'] }}"
      UI_TRAFFIC_STATS: "true"
  tags: wireguard,container

- ansible.builtin.include_role:
    name: applications
    tasks_from: watchtower
    apply:
      tags:
        - watchtower
        - container
  tags: always

- ansible.builtin.include_role:
    name: games
    tasks_from: portainer-agent
    apply:
      tags:
        - portainer-agent
        - container
  tags: always