---
- name: Create Wg-easy volume
  community.docker.docker_volume:
    state: present
    name: wireguard_data

- name: Run Wg-easy container
  community.docker.docker_container:
    name: wireguard
    image: ghcr.io/wg-easy/wg-easy:latest
    state: started
    restart_policy: always
    capabilities:
      - NET_ADMIN
      - SYS_MODULE
      - NET_RAW
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
      net.ipv4.ip_forward: 1
    network_mode: overlay_network
    ports:
      - 51820:51820/udp
    volumes:
      - wireguard_data:/etc/wireguard:Z
    env:
      WG_HOST: "{{ public_domain }}"
      PASSWORD: "{{ wg_password }}"
    labels:
      traefik.enable: "true"
      traefik.http.routers.wireguard.rule: Host(`wireguard.{{ private_domain }}`)
      traefik.http.routers.wireguard.entrypoints: "https"
      traefik.http.routers.wireguard.tls: "true"
      traefik.http.routers.wireguard.service: "wireguard"
      traefik.http.services.wireguard.loadbalancer.server.port: "51821"