---
- name: Create Wg-easy volume
  community.docker.docker_volume:
    state: present
    name: wireguard_data

- name: Run Wg-easy container
  community.docker.docker_container:
    name: wireguard
    image: ghcr.io/wg-easy/wg-easy:latest
    state: started
    restart_policy: always
    network_mode: overlay_network
    ports:
      - 51820:51820/udp
    volumes:
      - wireguard_data:/etc/wireguard
    capabilities:
      - NET_ADMIN
      - SYS_MODULE
      - NET_RAW
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
      net.ipv4.ip_forward: 1
    env:
      WG_HOST: "{{ public_domain }}"
      PASSWORD: "{{ wg_password }}"