---
- ansible.builtin.import_tasks: caddy.yml
  tags: caddy

- ansible.builtin.import_tasks: nextcloud.yml
  tags: nextcloud

- ansible.builtin.import_tasks: freshrss.yml
  tags: freshrss

- ansible.builtin.import_tasks: firefly-iii.yml
  tags: firefly