---
- name: Run Syncthing container
  containers.podman.podman_container:
    name: syncthing
    image: docker.io/syncthing/syncthing
    state: started
    restart_policy: always
    ports:
      - "{{ ports.syncthing }}:8384"
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    volumes:
      - "{{ volumes.syncthing }}:/var/syncthing:Z"