---
- name: Create a Firefly-iii network
  containers.podman.podman_network:
    name: firefly_network

- name: Create Firefly-iii volumes
  containers.podman.podman_volume:
    state: present
    name: firefly_db

- name: Run Mariadb container
  containers.podman.podman_container:
    name: firefly_db
    image: docker.io/library/mariadb
    state: started
    restart_policy: always
    volume:
      - firefly_db:/var/lib/mysql
    network: firefly_network
    env:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_PASSWORD: "{{ password }}"
      MYSQL_DATABASE: firefly
      MYSQL_USER: firefly

- name: Run Redis container
  containers.podman.podman_container:
    name: firefly_cache
    image: docker.io/library/redis
    state: started
    restart_policy: always
    network: firefly_network

- name: Run Firefly-iii container
  containers.podman.podman_container:
    name: firefly_app
    image: docker.io/fireflyiii/core
    state: started
    restart_policy: always
    publish:
      - 9319:8080/tcp
    volume:
      - "{{ rootless_volumes.firefly }}:/var/www/html/storage/upload:Z"
    network: firefly_network
    env:
      APP_ENV: production
      APP_KEY: rRJtexvy3m3NpZnfOSy1dWPCeLIsYbRb
      TZ: Europe/Paris
      DB_CONNECTION: mysql
      DB_PASSWORD: "{{ password }}"
      DB_DATABASE: firefly
      DB_USERNAME: firefly
      DB_HOST: firefly_db
      CACHE_DRIVER: redis
      REDIS_HOST: firefly_cache