---
- name: Create overlay network
  community.docker.docker_network:
    name: overlay_network

- name: Run Traefik
  ansible.builtin.include_role:
    name: production
    tasks_from: traefik
    apply:
      tags: traefik
  tags: traefik

- name: Run Syncthing
  ansible.builtin.include_role:
    name: production
    tasks_from: syncthing
    apply:
      tags: syncthing
  tags: syncthing

- name: Run filebrowser
  ansible.builtin.include_role:
    name: production
    tasks_from: filebrowser
    apply:
      tags: filebrowser
  tags: filebrowser