---
- name: Enable linger
  ansible.builtin.command: "loginctl enable-linger {{ ansible_user }}"
  become: true

- name: Install Podman
  ansible.builtin.package:
    name: podman
    state: present
  become: true

- name: Create container directory
  ansible.builtin.file:
    path: "{{ item.value }}"
    state: directory
  loop: "{{ rootless_volumes|dict2items }}"
  when: rootless_volumes is defined
  become: false

- name: Create container directory
  ansible.builtin.file:
    path: "{{ item.value }}"
    state: directory
  loop: "{{ rootfull_volumes|dict2items }}"
  when: rootfull_volumes is defined
  become: true