---
- name: Create Adguard Home volume
  community.docker.docker_volume:
    state: present
    volume_name: "{{ item }}"
  loop:
    - adguardhome_work
    - adguardhome_conf

- name: Run Adguard Home container
  community.docker.docker_container:
    name: adguardhome
    image: docker.io/adguard/adguardhome:latest
    state: started
    restart_policy: always
    recreate: true
    ports:
      - 3000:3000/tcp # Web UI
      - 53:53/tcp # Plain DNS server
      - 53:53/udp # Plain DNS server
    volumes:
      - adguardhome_work:/opt/adguardhome/work
      - adguardhome_conf:/opt/adguardhome/conf