---
- name: Create Filestash volume
  community.docker.docker_volume:
    state: present
    volume_name: filestash_data

- name: Run Filestash container
  community.docker.docker_container:
    name: filestash
    image: docker.io/machines/filestash:latest
    state: started
    restart_policy: always
    recreate: true
    network_mode: "{{ docker_network }}"
    volumes:
      - filestash_data:/app/data/state
    env:
      APPLICATION_URL: "https://file.{{ private_domain }}"
    labels:
      traefik.enable: "true"
      traefik.http.routers.filestash.rule: Host(`file.{{ private_domain }}`)
      traefik.http.routers.filestash.entrypoints: "https"
      traefik.http.routers.filestash.tls: "true"
      traefik.http.routers.filestash.service: "filestash"
      traefik.http.services.filestash.loadbalancer.server.port: "8334"