---
- name: Install Docker dependencies
  ansible.builtin.package:
    name:
      - ca-certificates
      - gnupg
    state: present
  tags: docker,packages

- name: Add Docker GPG key
  ansible.builtin.get_url:
    url: "https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg"
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
  tags: docker,packages

- name: Add Docker repo
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
  tags: docker,packages

- name: Install Docker
  ansible.builtin.package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - python3-docker
    state: present
  tags: docker,packages

- name: Enable Docker service
  ansible.builtin.systemd:
    name: docker.service
    state: started
    enabled: true
    scope: system
  tags: docker,services

- name: Create Docker network
  community.docker.docker_network:
    name: "{{ docker.network }}"
  tags: docker

- name: Create docker directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  loop:
    - "{{ docker.data }}"
    - "{{ docker.backup }}"
  tags: docker