---
- name: Create Docker NFS volume for Navidrome
  community.docker.docker_volume:
    state: present
    volume_name: music_nfs
    driver_options:
      type: "nfs"
      o: "addr={{ hostvars['vm-nas-01']['ansible_host'] }},ro,nfsvers=4"
      device: ":/music"

- name: Run Navidrome container
  community.docker.docker_container:
    name: navidrome
    image: docker.io/deluan/navidrome:latest
    state: started
    restart_policy: always
    recreate: true
    network_mode: "{{ docker_network }}"
    volumes:
      - music_nfs:/music
      - navidrome_data:/data
    env:
      ND_ENABLESHARING: "true"
      ND_BASEURL: "https://music.{{ private_domain }}"
      ND_SPOTIFY_ID: "{{ navidrome_spotify_client_id }}"
      ND_SPOTIFY_SECRET: "{{ navidrome_spotify_client_secret }}"
    labels:
      traefik.enable: "true"
      traefik.http.routers.navidrome.rule: Host(`music.{{ private_domain }}`)
      traefik.http.routers.navidrome.entrypoints: "https"
      traefik.http.routers.navidrome.tls: "true"
      traefik.http.routers.navidrome.service: "navidrome"
      traefik.http.services.navidrome.loadbalancer.server.port: "4533"