---
- name: Mount music NFS 
  ansible.posix.mount:
    src: "{{ hostvars['nas']['ansible_host'] }}:/music"
    path: "{{ docker.data }}/navidrome"
    opts: ro,hard,nfsvers=4
    state: mounted
    boot: true
    fstype: nfs

- name: Run Navidrome container
  community.docker.docker_container:
    name: navidrome
    image: docker.io/deluan/navidrome:latest
    state: started
    restart_policy: always
    restart: true
    network_mode: "{{ docker.network }}"
    volumes:
      - "{{ docker.data }}/navidrome:/music:ro"
      - navidrome_data:/data
    env:
      ND_ENABLESHARING: "true"
      ND_BASEURL: "https://music.{{ private_domain }}"
      ND_SPOTIFY_ID: "{{ navidrome_spotify_client_id }}"
      ND_SPOTIFY_SECRET: "{{ navidrome_spotify_client_secret }}"
    labels:
      traefik.enable: "true"
      traefik.http.routers.navidrome.rule: Host(`music.{{ private_domain }}`)
      traefik.http.routers.navidrome.entrypoints: "https"
      traefik.http.routers.navidrome.tls: "true"
      traefik.http.routers.navidrome.service: "navidrome"
      traefik.http.services.navidrome.loadbalancer.server.port: "4533"