---
- name: Mount sync NFS 
  ansible.posix.mount:
    src: "{{ hostvars['nas']['ansible_host'] }}:/sync"
    path: "{{ docker.data }}/syncthing"
    opts: rw,hard,nfsvers=4
    state: mounted
    boot: true
    fstype: nfs

- name: Run Syncthing container
  community.docker.docker_container:
    name: syncthing
    image: docker.io/syncthing/syncthing:latest
    state: started
    restart_policy: always
    recreate: true
    network_mode: "{{ docker.network }}"
    ports:
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    volumes:
      - "{{ docker.data }}/syncthing:/var/syncthing"
    labels:
      traefik.enable: "true"
      traefik.http.routers.syncthing.rule: Host(`sync.{{ private_domain }}`)
      traefik.http.routers.syncthing.entrypoints: "https"
      traefik.http.routers.syncthing.tls: "true"
      traefik.http.routers.syncthing.service: "syncthing"
      traefik.http.services.syncthing.loadbalancer.server.port: "8384"