---
- name: NFS volume mount
  community.docker.docker_volume:
    driver_options:
      type: nfs
      o: "addr={{ hostvars['nas']['ansible_host'] }},rw"
      device: :/UserData
    volume_name: user_data

- name: Run Syncthing container
  community.docker.docker_container:
    name: syncthing
    image: docker.io/syncthing/syncthing:latest
    state: started
    restart_policy: always
    restart: true
    network_mode: "{{ docker.network }}"
    ports:
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    volumes:
      - user_data:/var/syncthing
    labels:
      traefik.enable: "true"
      traefik.http.routers.syncthing.rule: Host(`sync.{{ private_domain }}`)
      traefik.http.routers.syncthing.entrypoints: "https"
      traefik.http.routers.syncthing.tls: "true"
      traefik.http.routers.syncthing.service: "syncthing"
      traefik.http.services.syncthing.loadbalancer.server.port: "8384"