---
- name: Create Traefik volume
  community.docker.docker_volume:
    state: present
    volume_name: traefik_data

- name: Template Traefik configuration to /tmp
  ansible.builtin.template:
    src: "traefik/{{ item }}.j2"
    dest: "/tmp/{{ item }}"
  loop:
    - traefik.yml
    - config.yml

- name: Create acme.json file to /tmp
  ansible.builtin.file:
    path: "/tmp/acme.json"
    state: touch
    mode: '0600'

- name: Run traefik container
  community.docker.docker_container:
    name: traefik
    image: docker.io/library/traefik:latest
    state: started
    restart_policy: always
    recreate: true
    network_mode: "{{ docker_network }}"
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_data:/etc/traefik
    env:
      OVH_ENDPOINT: "{{ ovh_endpoint }}"
      OVH_APPLICATION_KEY: "{{ ovh_application_key }}"
      OVH_APPLICATION_SECRET: "{{ ovh_application_secret }}"
      OVH_CONSUMER_KEY: "{{ ovh_consumer_key }}"
    labels:
      traefik.enable: "true"
      traefik.http.routers.traefik.rule: Host(`traefik.{{ private_domain }}`)
      traefik.http.routers.traefik.entrypoints: "https"
      traefik.http.routers.traefik.tls.certresolver: "ovh"
      traefik.http.routers.traefik.tls.domains[0].main: "{{ private_domain }}"
      traefik.http.routers.traefik.tls.domains[0].sans: "*.{{ private_domain }}"
      traefik.http.routers.traefik.service: "api@internal"

- name: Copy Traefik config to the Traefik container
  community.docker.docker_container_copy_into:
    container: traefik
    path: "/tmp/{{ item }}"
    container_path: "/etc/traefik/{{ item }}"
  loop:
    - config.yml
    - traefik.yml
    - acme.json

- name: Restart Traefik instance to use new configuration
  community.docker.docker_container:
    name: traefik
    state: started
    restart: true