---
- name: Create Gotify volumes
  community.docker.docker_volume:
    state: present
    name: gotify_data

- name: Run Gotify container
  community.docker.docker_container:
    name: gotify
    image: docker.io/gotify/server:latest
    state: started
    restart_policy: always
    network_mode: "{{ docker.network }}"
    volumes:
      - gotify_data/syncthing:/app/data"
    labels:
      traefik.enable: "true"
      traefik.http.routers.gotify.rule: Host(`gotify.{{ private_domain }}`)
      traefik.http.routers.gotify.entrypoints: "https"
      traefik.http.routers.gotify.tls: "true"
      traefik.http.routers.gotify.service: "gotify"
      traefik.http.services.gotify.loadbalancer.server.port: "80"