---
- name: Create SMB directories
  ansible.builtin.file:
    path: "{{ item['path'] }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  loop: "{{ smb_config['shares'] }}"

- name: Create UNIX users
  ansible.builtin.user:
    name: "{{ item['username'] }}"
    home: "{{ item['homedir'] }}"
    shell: /sbin/nologin
  loop: "{{ smb_config['users'] }}"

- name: Set Samba passwords
  shell: "printf '{{ item['password'] }}\n{{ item['password'] }}\n' | smbpasswd -a -s {{ item['username'] }}"
  loop: "{{ smb_config['users'] }}"

- name: Template Samba configuration
  ansible.builtin.template:
    src: smb.conf.j2
    dest: "/etc/samba/smb.conf"

- name: Restart Samba service
  ansible.builtin.systemd_service:
    name: smbd.service
    state: restarted
    scope: system