---
- name: Create UNIX users
  ansible.builtin.user:
    name: "{{ item['username'] }}"
    home: "{{ item['homedir'] }}"
    group: users
    shell: /sbin/nologin
  loop: "{{ smb_users }}"

- name: Set Samba passwords
  shell: "printf '{{ item['password'] }}\n{{ item['password'] }}\n' | smbpasswd -a -s {{ item['username'] }}"
  loop: "{{ smb_users }}"