---
- name: Install NFS package
  ansible.builtin.apt:
    name: nfs-kernel-server
    state: present

- name: Enable NFS service
  ansible.builtin.systemd_service:
    name: nfs-server.service
    state: started
    enabled: true
    scope: system