---
- name: Install SMB on Debian based OS
  ansible.builtin.import_tasks: install_smb_debian.yml
  when: ansible_distribution in ["Ubuntu", "Debian"]
  tags: smb,debian

- name: Configure Samba server
  ansible.builtin.import_tasks: configure_smb.yml
  tags: smb