---
- name: Install NUT
  ansible.builtin.apt:
    name: nut
    state: present

- name: Enable NUT services
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: started
    enabled: true
    scope: system
  loop:
    - nut-server.service
    - nut-client.service
    - nut-monitor.service