---
- name: Listen to localhost
  ansible.builtin.lineinfile:
    path: /etc/nut/upsd.conf
    state: present
    regexp: '^LISTEN'
    line: 'LISTEN 127.0.0.1 3493'

- name: Create UPSMON primary user
  ansible.builtin.blockinfile:
    path: /etc/nut/upsd.users
    state: present
    block: |
      # Define user credentials for monitoring the UPS
      [upsmon]
        password = {{ nut_upsmon_password }}
        upsmon primary

- name: Ensure UPSMON config is correct
  ansible.builtin.lineinfile:
    path: /etc/nut/upsmon.conf
    state: present
    regexp: "{{ item['regexp'] }}"
    line: "{{ item['line'] }}"
  loop:
    - { regexp: '^MONITOR', line: 'MONITOR eaton3s@localhost 1 upsmon {{ nut_upsmon_password }} primary' }
    - { regexp: '^SHUTDOWNCMD', line: 'SHUTDOWNCMD "/sbin/shutdown -h +0"' }
    - { regexp: '^MINSUPPLIES', line: 'MINSUPPLIES 1' }
    - { regexp: '^POWERDOWNFLAG', line: 'POWERDOWNFLAG /etc/killpower' }