---
- name: Edit SSHD configuration
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: "{{ item['regexp'] }}"
    line: "{{ item['line'] }}"
  loop:
    - { regexp: '^#?\s*PermitRootLogin', line: 'PermitRootLogin prohibit-password' }
    - { regexp: '^#?\s*PasswordAuthentication', line: 'PasswordAuthentication no' }
    - { regexp: '^#?\s*PermitEmptyPasswords', line: 'PermitEmptyPasswords no' }

- name: Reload SSHD service
  ansible.builtin.systemd_service:
    name: sshd.service
    state: reloaded
    scope: system