---
- name: Install packages
  ansible.builtin.package:
    name: "{{ common.packages }}"
    state: present
  when: common.packages is defined

- name: Enable services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
    scope: system
  loop: "{{ common.services }}"
  when: common.services is defined

- name: Remove dependencies
  ansible.builtin.apt:
    autoremove: yes
    purge: true