---
- name: Install Packages
  ansible.builtin.package:
    name: "{{ packages }}"
    state: present
  when: packages is defined
  become: true
  tags: packages

- name: Create volumes
  ansible.builtin.file:
    path: "{{ item.value }}"
    state: directory
  loop: "{{ volumes|dict2items }}"
  when: volumes is defined
  tags: volumes

- ansible.builtin.import_tasks: systemd.yml
  tags: systemd