---
- name: Enable linger
  ansible.builtin.command: "loginctl enable-linger {{ ansible_user }}"
  become: true

- name: Install Podman
  ansible.builtin.package:
    name:
      - podman
    state: present
  become: true

- ansible.builtin.import_tasks: volumes.yml
- ansible.builtin.import_tasks: services.yml