---
- name: Install Packages
  ansible.builtin.package:
    name: "{{ packages }}"
    state: present
  when: packages is defined
  become: true
  tags: packages

- name: Create volumes directories
  ansible.builtin.file:
    path: "{{ item.value }}"
    state: directory
  loop: "{{ volumes|dict2items }}"
  when: volumes is defined
  tags: volumes

- name: Enable system services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
    scope: system
  loop: "{{ services.system }}"
  when: services.system is defined
  become: true

- name: Enable user services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
    scope: user
  loop: "{{ services.user }}"
  when: services.user is defined

- name: Enable linger
  ansible.builtin.command: "loginctl enable-linger {{ ansible_user }}"
  become: true