---
- name: Install Packages
  ansible.builtin.package:
    name: "{{ packages }}"
    state: present
  when: packages is defined
  become: true
  tags: packages

- name: Create volumes directories
  ansible.builtin.file:
    path: "{{ item.value }}"
    state: directory
  loop: "{{ volumes|dict2items }}"
  when: volumes is defined
  tags: volumes

- name: Enable Systemd services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
    scope: system
  loop: "{{ services }}"
  when: services is defined
  become: true
  tags: services