---
- name: Enable system services
  ansible.builtin.systemd:
    name: podman-restart.service
    state: started
    enabled: true
    scope: system
  loop:
    - podman-restart.service
    - qemu-guest-agent
  become: true

- name: Enable user services
  ansible.builtin.systemd:
    name: podman-restart.service
    state: started
    enabled: true
    scope: user
  become: false