---
- name: Create rootfull volumes
  ansible.builtin.file:
    path: "{{ item.value }}"
    state: directory
  loop: "{{ rootfull_volumes|dict2items }}"
  when: rootfull_volumes is defined
  become: true

- name: Create rootless volumes
  ansible.builtin.file:
    path: "{{ item.value }}"
    state: directory
  loop: "{{ rootless_volumes|dict2items }}"
  when: rootless_volumes is defined
  become: false