---
- name: Create Rclone config directory
  ansible.builtin.file:
    path: /root/.config/rclone
    state: directory
    mode: '0700'

- name: Template Rclone config & backup script
  ansible.builtin.template:
    src: "{{ item['src'] }}"
    dest: "{{ item['dest'] }}"
    mode: "{{ item['mode'] }}"
  loop:
    - { src: 'offsite_backup.sh.j2', dest: '/usr/local/bin/offsite_backup.sh', mode: '0700' }
    - { src: 'rclone.conf.j2', dest: '/root/.config/rclone/rclone.conf', mode: '0600' }

- name: Create daily backup with Rclone
  ansible.builtin.cron:
    name: "Send backup to remote storage"
    state: present
    minute: "0"
    hour: "3"
    user: "{{ ansible_user }}"
    job: "/usr/local/bin/offsite_backup.sh"