---
- ansible.builtin.import_tasks: minecraft.yml
  tags: minecraft,container

- ansible.builtin.import_tasks: terraria.yml
  tags: terraria,container

- ansible.builtin.import_tasks: playit.yml
  tags: playit,playit.gg

- ansible.builtin.include_role:
    name: containers/production
    tasks_from: watchtower
    apply:
      tags:
        - watchtower
        - container
  tags: always