---
- ansible.builtin.import_tasks: minecraft.yml
  tags: minecraft,container

- ansible.builtin.import_tasks: terraria.yml
  tags: terraria,container

- ansible.builtin.import_tasks: playit.yml
  tags: playit,playit.gg