---
- name: Install Zabbix Agent
  ansible.builtin.package:
    name: zabbix-agent2
    state: present

- name: Edit Zabbix Agent configuration if exist
  ansible.builtin.lineinfile:
    path: /etc/zabbix/zabbix_agent2.conf
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - { regexp: '^Hostname=', line: 'Hostname={{ ansible_hostname }}' }
    - { regexp: '^Server=', line: "Server={{ hostvars[groups['zabbix'][0]].ansible_default_ipv4.address }}" }
    - { regexp: '^ServerActive=', line: "ServerActive={{ hostvars[groups['zabbix'][0]].ansible_default_ipv4.address }}" }

- name: Enable Qemu Guest Agent service
  ansible.builtin.systemd:
    name: zabbix-agent2.service
    state: started
    enabled: true
    scope: system