---
- name: Install Samba packages
  ansible.builtin.apt:
    name:
      - samba
      - samba-vfs-modules
    state: present
  tags: samba

- name: Enable Samba services
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: started
    enabled: true
    scope: system
  loop:
    - smbd.service
    - nmbd.service
  tags: samba

- name: Install NFS package
  ansible.builtin.apt:
    name: nfs-kernel-server
    state: present
  tags: nfs

- name: Enable NFS service
  ansible.builtin.systemd_service:
    name: nfs-server.service
    state: started
    enabled: true
    scope: system
  tags: nfs