---
- name: Set timezone to {{ timezone }}
  community.general.timezone:
    name: "{{ timezone }}"
  tags: common,timezone

- name: Install common packages
  ansible.builtin.package:
    name: "{{ common['packages'] }}"
    state: present
  when: common['packages'] is defined
  tags: common

- name: Enable common services
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: started
    enabled: true
    scope: system
  loop: "{{ common['services'] }}"
  when: common['services'] is defined
  tags: common

- name: Configure SSH
  ansible.builtin.import_tasks: configure_ssh.yml
  tags: common,ssh