---
- name: Create share directories
  ansible.builtin.file:
    path: "{{ item['path'] }}"
    state: directory
    group: users
    mode: '2770'
  loop: "{{ nfs_shares }}"

- name: Set default ACL for shared directories
  ansible.posix.acl:
    path: "{{ item['path'] }}"
    etype: group
    permissions: rwx
    default: true
    recursive: true
    state: present
  loop: "{{ nfs_shares }}"

- name: Create root mount point for NFS
  ansible.builtin.file:
    path: /export
    state: directory
    mode: '0755'

- name: Bind mount directories to the NFS root
  ansible.posix.mount:
    src: "{{ item['path'] }}"
    path: "/export/{{ item['path'] | basename }}"
    opts: bind
    state: mounted
    fstype: none
  loop: "{{ nfs_shares }}"

- name: Template NFS configuration
  ansible.builtin.template:
    src: exports.j2
    dest: "/etc/exports"

- name: Export the shares
  ansible.builtin.command: exportfs -ar

- name: Reload NFS service
  ansible.builtin.systemd_service:
    name: nfs-server.service
    state: reloaded
    scope: system