---
- name: Install NFS & SMB on Debian based OS
  ansible.builtin.import_tasks: install_nfs_smb_debian.yml
  when: ansible_distribution in ["Ubuntu", "Debian"]
  tags: nfs,smb,debian

- name: Configure Samba server
  ansible.builtin.import_tasks: configure_smb_shares.yml
  tags: smb

- name: Configure NFS server
  ansible.builtin.import_tasks: configure_nfs_shares.yml
  tags: nfs