---
- name: Deploy the fileserver
  hosts: vm-files-01
  ignore_unreachable: true
  become: true
  roles:
    - common
    - crowdsec
    - fileserver

- name: Configure Proxmox host
  hosts: srv-pve-01
  ignore_unreachable: true
  become: true
  roles:
    - common
    - crowdsec
    - rclone_backup
    - ups_monitoring

- name: Install & configure Docker
  hosts: docker
  ignore_unreachable: true
  become: true
  roles:
    - common
    - crowdsec
    - docker_setup
    - docker_containers