---
- hosts: nas,pve
  gather_facts: true
  ignore_unreachable: true
  become: true
  roles:
    - common

- hosts: pbe
  gather_facts: true
  ignore_unreachable: true
  become: true
  roles:
    - common
    - backup