---
- name: Configure Proxmox host
  hosts: srv-pve-01
  ignore_unreachable: true
  become: true
  roles:
    - common
    - proxmox

- name: Configure vm-services-01
  hosts: vm-services-01
  ignore_unreachable: true
  become: true
  roles:
    - common
    - samba
    - docker_setup
    - docker_containers

- name: Configure vm-games-01
  hosts: vm-games-01
  ignore_unreachable: true
  become: true
  roles:
    - common
    - docker_setup
    - docker_containers