---
- hosts: all
  gather_facts: true
  ignore_unreachable: true
  become: true
  roles:
    - common

- hosts: pve
  gather_facts: true
  ignore_unreachable: true
  become: true
  roles:
    - backup

- hosts: games
  gather_facts: true
  ignore_unreachable: true
  become: true
  roles:
    - playit