---
- hosts: apps
  gather_facts: true
  become: true
  roles:
    - common
    - containers/all
    - containers/applications

- hosts: games
  gather_facts: true
  become: true
  roles:
    - common
    - containers/all
    - containers/games

- hosts: vpn
  gather_facts: true
  become: true
  roles:
    - common
    - containers/all
    - containers/vpn