---
- hosts: apps
  gather_facts: true
  ignore_unreachable: true
  become: true
  roles:
    - common
    - docker
    - containers/applications

- hosts: games
  gather_facts: true
  ignore_unreachable: true
  become: true
  roles:
    - common
    - docker
    - playit
    - containers/games

- hosts: vpn
  gather_facts: true
  ignore_unreachable: true
  become: true
  roles:
    - common
    - docker
    - containers/vpn