---
- hosts: media
  gather_facts: true
  become: true
  tasks:
    - name: Execute common tasks
      ansible.builtin.include_tasks:
        file: ../tasks/common.yml
        apply: { tags: common }
      tags: always

    - name: Install Docker
      ansible.builtin.include_tasks:
        file: ../tasks/docker.yml
        apply: { tags: docker }
      tags: always

    - name: Deploy containers
      ansible.builtin.include_tasks: 
        file: "../tasks/containers/{{ task_item }}.yml"
        apply: { tags: "{{ task_item }}" }
      tags: always
      loop:
        - jellyfin
        - jellyseerr
        - lidarr
        - prowlarr
        - radarr
        - qbittorrent
        - watchtower
      loop_control:
        loop_var: task_item