---
- hosts: production
  gather_facts: true
  become: true

  tasks:
    - name: Execute common tasks
      ansible.builtin.import_tasks: tasks/common.yml
      tags: common

    - name: Deploy containers
      ansible.builtin.import_tasks: "tasks/{{ item }}.yml"
      loop:
        - baikal
        - caddy
        - firefly-iii
        - freshrss
        - syncthing
        - watchtower
        - portainer
        - filebrowser
        - uptime-kuma
      tags: containers