---
- hosts: production
  gather_facts: true
  become: true

  tasks:
    - name: Configure server
      ansible.builtin.import_tasks: tasks/common.yml

    - name: Deploy Docker apps
      ansible.builtin.import_tasks: "tasks/{{ item }}.yml"
      loop:
        - caddy
        - baikal
        - firefly-iii
        - freshrss
        - syncthing