---
- hosts: production
  gather_facts: true
  become: true

  tasks:
    - name: Execute common tasks
      ansible.builtin.include_tasks: ../tasks/common.yml

    - name: Deploy containers
      ansible.builtin.include_tasks: "../tasks/containers/{{ task_item }}.yml"
      loop:
        - baikal
        - caddy
        - firefly-iii
        - freshrss
        - syncthing
        - watchtower
        - portainer
        - filebrowser
        - uptime-kuma
      loop_control:
        loop_var: task_item