---
- hosts: production
  gather_facts: true
  become: true
  tasks:
    - name: Install Qemu Guest Agent
      ansible.builtin.include_tasks:
        file: ../tasks/qemu.yml
        apply: { tags: qemu }
      tags: always

    - name: Install Docker
      ansible.builtin.include_tasks:
        file: ../tasks/docker.yml
        apply: { tags: docker }
      tags: always

    - name: Deploy containers
      ansible.builtin.include_tasks: 
        file: "../tasks/containers/{{ task_item }}.yml"
        apply: { tags: "{{ task_item }}" }
      tags: always
      loop:
        - baikal
        - syncthing
        - filebrowser
        - firefly-iii
        - freshrss
        - portainer
        - traefik
        - uptime-kuma
        - watchtower
      loop_control:
        loop_var: task_item