---
- hosts: apps
  gather_facts: true
  ignore_unreachable: true
  become: true
  roles:
    - common
    - containers
    - containers/applications

- hosts: games
  gather_facts: true
  ignore_unreachable: true
  become: true
  roles:
    - common
    - containers
    - containers/games