---
- name: Configure Swarm
  ansible.builtin.import_playbook: configure_swarm.yml

- name: Configure Zabbix
  ansible.builtin.import_playbook: configure_zabbix.yml

- name: Deploy apps
  ansible.builtin.import_playbook: deploy_apps.yml

- name: Deploy vpn
  ansible.builtin.import_playbook: deploy_vpn.yml

- name: Deploy media
  ansible.builtin.import_playbook: deploy_media.yml

- name: Deploy games
  ansible.builtin.import_playbook: deploy_games.yml