---
- name: Install applications
  ansible.builtin.import_playbook: applications.yml

- name: Install games
  ansible.builtin.import_playbook: games.yml

- name: Deploy backup
  ansible.builtin.import_playbook: backup.yml

- name: Install VPN
  ansible.builtin.import_playbook: vpn.yml

- name: Deploy maintenance
  ansible.builtin.import_playbook: maintenance.yml