---
- name: Init swarm
  ansible.builtin.import_playbook: init_swarm.yml

- name: Deploy admin
  ansible.builtin.import_playbook: deploy_admin.yml

- name: Deploy apps
  ansible.builtin.import_playbook: deploy_apps.yml

- name: Deploy games
  ansible.builtin.import_playbook: deploy_games.yml

- name: Deploy pve
  ansible.builtin.import_playbook: deploy_pve.yml