---
- name: Import swarm playbook
  ansible.builtin.import_playbook: swarm.yml

- name: Import vpn playbook
  ansible.builtin.import_playbook: vpn.yml

- name: Import production playbook
  ansible.builtin.import_playbook: production.yml

- name: Import games playbook
  ansible.builtin.import_playbook: games.yml