---
- name: Deploy apps
  ansible.builtin.import_playbook: deploy_apps.yml

- name: Deploy vpn
  ansible.builtin.import_playbook: deploy_vpn.yml

- name: Deploy games
  ansible.builtin.import_playbook: deploy_games.yml