---
- name: Install apps
  ansible.builtin.import_playbook: playbook_apps.yml

- name: Install games
  ansible.builtin.import_playbook: playbook_games.yml

- name: Deploy backup
  ansible.builtin.import_playbook: playbook_backup.yml

- name: Install VPN
  ansible.builtin.import_playbook: playbook_vpn.yml

- name: Deploy maintenance
  ansible.builtin.import_playbook: playbook_maintenance.yml