---
- hosts: swarm
  gather_facts: true
  become: true
  tasks:
    - name: Install Docker
      ansible.builtin.include_tasks:
        file: ../tasks/docker.yml
        apply: { tags: docker }
      tags: always

    - name: Setup Docker Swarm
      ansible.builtin.include_tasks:
        file: ../tasks/swarm.yml
        apply: { tags: swarm }
      tags: always