---
- hosts: vpn
  gather_facts: true
  become: true

  tasks:
    - name: Execute common tasks
      ansible.builtin.import_tasks: tasks/common.yml
      tags: common

    - name: Deploy containers
      ansible.builtin.import_tasks: "tasks/{{ item }}.yml"
      loop:
        - wireguard
        - watchtower
      tags: containers