---
- hosts: vpn
  gather_facts: true
  become: true

  tasks:
    - name: Execute common tasks
      ansible.builtin.include_tasks: ../tasks/common.yml

    - name: Deploy containers
      ansible.builtin.include_tasks: "../tasks/{{ task_item }}.yml"
      loop:
        - wireguard
        - watchtower
      loop_control:
        loop_var: task_item