---
- hosts: vpn
  gather_facts: true
  become: true

  tasks:
    - name: Execute common tasks
      ansible.builtin.import_tasks: tasks/common.yml
      tags: common

    - name: Deploy WG-easy app
      ansible.builtin.import_tasks: tasks/wg-easy.yml
      tags: wg-easy