---
- name: Create a Firefly-iii network
  containers.podman.podman_network:
    name: firefly_network

- name: Create Firefly-iii volumes
  containers.podman.podman_volume:
    state: present
    name: "{{ item }}"
  loop: 
    - firefly_upload
    - firefly_db

- name: Run Mariadb container
  containers.podman.podman_container:
    name: firefly_db
    image: docker.io/library/mariadb
    state: started
    restart_policy: always
    volume:
      - firefly_db:/var/lib/mysql
    network: firefly_network
    env:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_PASSWORD: "{{ server_password }}"
      MYSQL_DATABASE: firefly
      MYSQL_USER: firefly

- name: Run Firefly-iii container
  containers.podman.podman_container:
    name: firefly_app
    image: docker.io/fireflyiii/core
    state: started
    restart_policy: always
    publish:
      - 9319:8080/tcp
    volume:
      - firefly_upload:/var/www/html/storage/upload:Z
    network: firefly_network
    env:
      APP_ENV: local
      APP_KEY: rRJtexvy3m3NpZnfOSy1dWPCeLIsYbRb
      TZ: Europe/Paris
      DB_HOST: firefly_db
      DB_DATABASE: firefly
      DB_USERNAME: firefly
      DB_PASSWORD: "{{ server_password }}"