---
- name: Run Wireguard container
  community.docker.docker_container:
    name: wireguard
    image: docker.io/linuxserver/wireguard:latest
    state: started
    restart_policy: always
    network_mode: bridge
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctl:
      - net.ipv4.conf.all.src_valid_mark=1
    ports:
      - 51820:51820/udp
    volumes:
      - "{{ container_volumes.wireguard }}:/config"
      - /lib/modules:/lib/modules
    env:
      TZ: Europe/Paris
      SERVERURL: wireguard.endlessazurite.fr
      PEERS: red-taurus,cyan-fox