---
- name: Run Wireguard container
  community.docker.docker_container:
    name: wireguard
    image: ghcr.io/wg-easy/wg-easy
    state: started
    restart_policy: always
    capabilities:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
      net.ipv4.ip_forward: 1
    ports:
      - 51822:51820/udp
      - 51821:51821/tcp
    volumes:
      - "{{ container_volumes.wireguard }}:/etc/wireguard"
      - /lib/modules:/lib/modules
    env:
      WG_HOST: wireguard.endlessazurite.fr
      PASSWORD: kPThOMOOZmSlvj6y