---
- name: Create Portainer volume
  community.docker.docker_volume:
    state: present
    name: portainer_data

- name: Run Portainer container
  community.docker.docker_container:
    name: portainer
    image: docker.io/portainer/portainer-ce:latest
    state: started
    restart_policy: always
    restart: true
    network_mode: "{{ docker.network }}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      traefik.enable: "true"
      traefik.http.routers.portainer.rule: Host(`portainer.{{ private_domain }}`)
      traefik.http.routers.portainer.entrypoints: "https"
      traefik.http.routers.portainer.tls: "true"
      traefik.http.routers.portainer.service: "portainer"
      traefik.http.services.portainer.loadbalancer.server.port: "9000"