---
- name: Create Sftpgo volume
  community.docker.docker_volume:
    state: present
    name: sftpgo_config

- name: Run Sftpgo container
  community.docker.docker_container:
    name: sftpgo
    image: docker.io/drakkan/sftpgo:alpine
    state: started
    restart_policy: always
    restart: true
    network_mode: "{{ docker.network }}"
    ports:
      - 2022:2022
    volumes:
      - "{{ docker.data }}:/srv/sftpgo/data"
      - "{{ docker.backup }}:/srv/sftpgo/backup"
      - sftpgo_config:/var/lib/sftpgo
    labels:
      traefik.enable: "true"
      traefik.http.routers.sftpgo.rule: Host(`files.{{ private_domain }}`)
      traefik.http.routers.sftpgo.entrypoints: "https"
      traefik.http.routers.sftpgo.tls: "true"
      traefik.http.routers.sftpgo.service: "sftpgo"
      traefik.http.services.sftpgo.loadbalancer.server.port: "8080"