---
- name: Create Stirling PDF volumes
  community.docker.docker_volume:
    state: present
    name: "{{ item }}"
  loop:
    - stirling_data
    - stirling_config

- name: Run Stirling PDF container
  community.docker.docker_container:
    name: stirlingpdf
    image: docker.io/frooodle/s-pdf:latest
    state: started
    restart_policy: always
    restart: true
    network_mode: "{{ docker.network }}"
    volumes:
      - stirling_data:/usr/share/tessdata
      - stirling_config:/configs
    env:
      DOCKER_ENABLE_SECURITY: "false"
      INSTALL_BOOK_AND_ADVANCED_HTML_OPS: "false"
      LANGS: fr_FR
    labels:
      traefik.enable: "true"
      traefik.http.routers.stirling.rule: Host(`pdf.{{ private_domain }}`)
      traefik.http.routers.stirling.entrypoints: "https"
      traefik.http.routers.stirling.tls: "true"
      traefik.http.routers.stirling.service: "stirling"
      traefik.http.services.stirling.loadbalancer.server.port: "8080"